### ISSUE TITLE
What is the meaning of "curAugNum" in the file "sep_HHAR_data.py"?

### ISSUE THREAD

**Issue by oiwio** [yscacaca/HHAR-Data-Process#1]
Hello, I have read most code of the data processing, but still had some problems. 
1. What is the meaning of "curAugNum" in the file "sep_HHAR_data.py"?
2. I noticed that you use  "abs(curTime - startTime)<5 as the time interval, how can we make sure the "time window" with the same width(or maybe they don't need to be the same width?)
3. What is the effect of adding Gaussian noise in this case?

Thanks for your patient to read about the above!!!!

**Comment by yscacaca** [comment]
Hi,

1. "curAugNum" means the number of augmented data we want to generate for each existing sample in the training dataset. curAugNum = 0 means that we won't use data augmentation.

2. For each time interval, we artificially add a data point with [t = fftSpan and acc/gyro = last value](https://github.com/yscacaca/HHAR-Data-Process/blob/master/sep_HHAR_data.py#L83). And then interp1d and fft will be applied to this interval.

3. Gaussian noise is the data augmentation strategy we used. Sensing data (such as IMU data) from mobile and embedded devices are noise due to many reasons. So we add Gaussian noise to their values and time stamps. Data augmentation can improve the final peformance a little bit.
As I said before, curAugNum controls the number of augmented data. 

I hope these answers can help you.

**Comment by oiwio** [comment]
Thanks for your help!!! And can you tell me what is the difference between the mode "one_user_out" and "one_model_out"? Can I think the process like that, first, we set a time interval "5" (second?) then we will generate some Gaussian noise into a each time interval, if the width still < (window width) we will add the  t = fftSpan and acc/gyro = last value. This data series is a new time interval data that will be used fft transform？

**Comment by oiwio** [comment]
Thanks for your help!!! And can you tell me what is the difference between the mode "one_user_out" and "one_model_out"? Can I think the process like that, first, we set a time interval "5" (second?) ,if the width < (window width) we will add the t = fftSpan and acc/gyro = last value. Then we will generate some Gaussian noise into a each time interval. This data series is a new time interval data that will be used fft transform？

**Comment by yscacaca** [comment]
"one_user_out" and "one_model_out" are two modes for the evaluation.
In the "one_user_out" mode, all data from a specific user is used as the testing dataset. And data from all other users are used as the training dataset. Similarly, "one_model_out" selects one device out for testing.
So this generated dataset is used to evaluate the generalization ability of a model for users or devices that haven't seen before. Btw, I've only tested "one_user_out" before, so "one_model_out" dataset hasn't been fully tested before with the deepSense model.

The process is correct. Yet the length of time interval is not 5 second. I cannot remember the exact unit, since it relates to the time stamp of sensing data. You can read the code to figure out the detail, but I guess it should be 0.5 second.

**Comment by oiwio** [comment]
Hi, I still have some questions about the code of data processing. I noticed that you don't transform the original data as the training data, but use the original data + Gaussian noise data as the interpolation function and then generate 30 new point to feed to fft transformation so that we get the training data. I want to know why you process the data like that? Why you didn't use the original data + Gaussian noise data as the training data?

**Comment by yscacaca** [comment]
I use the original data as the training data. [See here.](https://github.com/yscacaca/HHAR-Data-Process/blob/master/sep_HHAR_data.py#L106)

**Comment by oiwio** [comment]
刚刚看到您是论文的第一作者。。。还是个国人，我就索性用中文了。。。因为我看到您下边的傅里叶变换的函数里用的插值的三十条数据进行的傅里叶变换，变换以后得到60条，再加上陀螺仪数据的60条，构成了120条的训练数据，同时对应一个curOut, 这儿的原始数据增加高斯噪声以后并没有直接作为训练数据，是不是我的理解上出现了偏差呢。。。循环太多。。代码看起来有点吃力，麻烦您了！

**Comment by yscacaca** [comment]
[从这儿](https://github.com/yscacaca/HHAR-Data-Process/blob/master/sep_HHAR_data.py#L104)开始加噪声的循环，[第一次循环](https://github.com/yscacaca/HHAR-Data-Process/blob/master/sep_HHAR_data.py#L106)是不加噪声的。[之后的curAugNum-1次](https://github.com/yscacaca/HHAR-Data-Process/blob/master/sep_HHAR_data.py#L110)是加噪声的。这里的确写得比较乱。

**Comment by oiwio** [comment]
我理解这段代码的意思，但是我看到下面的傅里叶变换并不是把添加过噪声的数据拿出去进行变换的，而是把添加过噪声的数据和时间作为参数传入插值函数里，[从而把插值的30条数据进行变换的](https://github.com/yscacaca/HHAR-Data-Process/blob/master/sep_HHAR_data.py#L124)，是不是我代码理解错了呢？

**Comment by yscacaca** [comment]
[差值函数在这吧: accInterp = interp1d(curTimeList, curAccList)](https://github.com/yscacaca/HHAR-Data-Process/blob/master/sep_HHAR_data.py#L121)，[当augIdx == 0的时候](https://github.com/yscacaca/HHAR-Data-Process/blob/master/sep_HHAR_data.py#L106)没加噪声啊

**Comment by yscacaca** [comment]
我好像理解你什么意思，差值的时间accInterpTime的确不是原来的时间，因为fft的关系，需要在时间上等距的一些samples。这也是我们为什么做差值。

**Comment by oiwio** [comment]
我的意思是[accInterpVal](https://github.com/yscacaca/HHAR-Data-Process/blob/master/sep_HHAR_data.py#L123)是一个(3,10)的array, 然后下面[傅里叶变换](https://github.com/yscacaca/HHAR-Data-Process/blob/master/sep_HHAR_data.py#L124)包括[添加进curSenData](https://github.com/yscacaca/HHAR-Data-Process/blob/master/sep_HHAR_data.py#L145)里都是用的这30条插值数据经过变换的结果。原始的数据（包括添加噪声的过程）是不是就是用来生成训练数据的，训练的数据就是我们插值经过傅里叶变换得来的？

**Comment by yscacaca** [comment]
是是，都不是原始的，fft的输入都是插值得来的。原始数据时间不是均匀sample的，用起来不方便，所以都先插值。不好意思，我这有点晚所以前面看回复都是跳着看的.....所以没理解错你意思了

**Comment by oiwio** [comment]
三点啦，你那儿。早点休息，有问题我再打扰你。。。晚安～～

**Comment by yscacaca** [comment]
拜~

**Comment by oiwio** [comment]
accNoiseVar gyroNoiseVar timeNoiseVar 这三个概率分布的标准差的值是怎么确定的呢？
还有后面引入的wide和wideScaleFactor，这个东西是不是可以理解为类似滑动窗口一样的东西，因为数据块中确实有很多数据重合了。

**Comment by yscacaca** [comment]
accNoiseVar gyroNoiseVar timeNoiseVar 这三个值是一篇paper的经验结果，我就直接用上了。wide是窗口的大小，wideScaleFactor是每次滑动的大小

**Comment by yscacaca** [comment]
accNoiseVar gyroNoiseVar timeNoiseVar 这三个值是一篇paper的经验结果，我就直接用上了。wide是窗口的大小，wide/wideScaleFactor是每次滑动的大小

**Comment by oiwio** [comment]
SampSpan的作用是什么呢？为什么经常有startTime - lastTime >= SampSpan 为False 导致curData_Sep为空的情况？

**Comment by yscacaca** [comment]
startTime - lastTime >= SampSpan 是用来保证当前的data有没有窗口的wide那么宽。

**Comment by oiwio** [comment]
没有窗口宽的话，这段数据被丢弃，是这样的么，我现在只提取了walk数据，然后用walk的数据来进行UserID的识别，但是提取数据的过程中发现，有超过一半的curData_Sep为空。。。

**Comment by yscacaca** [comment]
这里具体的逻辑我也有点记不清了，我等空了看看，你可以试试吧窗口变小。
