### ISSUE TITLE
Dataset stats

### ISSUE THREAD

**Issue by anjanaw** [yscacaca/HHAR-Data-Process#6]
Hello,
Can you mention the sampling rate of the original dataset (Activity recognition exp). 
Also explain why the data is interpolated before applying FFT? Is this due to sampling rate?

**Comment by yscacaca** [comment]
The sampling rate is around 50hz to 100hz (depending on the devices). 
We use interpolated for two reasons. 1) sampling rates may not be the same. 2) the sensor samples are not uniformly separated over the time (the sensor sampling process can be blocked for a very short period of time due to high CPU workloads)
